### ISSUE TITLE
25 DLLs added to VS2015 C# project during nuget update from 2.2.0 to 3.0.0

### ISSUE THREAD

**Issue by jfcardinal** [EamonNerbonne/a-vs-an#2]
I just updated AvsAn from 2.2.0 to 3.0.0 via nuget in a VS2015 C# project. During the upgrade, 25 DLLs were added to the project. (list below)

Is this expected?

Did I do (or not do) something to trigger the addition of the DLLs?

-----------

packages\Microsoft.Win32.Primitives.4.3.0\lib\net46\Microsoft.Win32.Primitives.dll
packages\System.AppContext.4.3.0\lib\net46\System.AppContext.dll
packages\System.Console.4.3.0\lib\net46\System.Console.dll
packages\System.Diagnostics.DiagnosticSource.4.3.0\lib\net46\System.Diagnostics.DiagnosticSource.dll
packages\System.Diagnostics.Tracing.4.3.0\lib\net462\System.Diagnostics.Tracing.dll
packages\System.Globalization.Calendars.4.3.0\lib\net46\System.Globalization.Calendars.dll
packages\System.IO.4.3.0\lib\net462\System.IO.dll
packages\System.IO.Compression.4.3.0\lib\net46\System.IO.Compression.dll
packages\System.IO.Compression.ZipFile.4.3.0\lib\net46\System.IO.Compression.ZipFile.dll
packages\System.IO.FileSystem.4.3.0\lib\net46\System.IO.FileSystem.dll
packages\System.IO.FileSystem.Primitives.4.3.0\lib\net46\System.IO.FileSystem.Primitives.dll
packages\System.Net.Http.4.3.0\lib\net46\System.Net.Http.dll
packages\System.Net.Sockets.4.3.0\lib\net46\System.Net.Sockets.dll
packages\System.Reflection.4.3.0\lib\net462\System.Reflection.dll
packages\System.Runtime.4.3.0\lib\net462\System.Runtime.dll
packages\System.Runtime.Extensions.4.3.0\lib\net462\System.Runtime.Extensions.dll
packages\System.Runtime.InteropServices.4.3.0\lib\net462\System.Runtime.InteropServices.dll
packages\System.Runtime.InteropServices.RuntimeInformation.4.3.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll
packages\System.Security.Cryptography.Algorithms.4.3.0\lib\net461\System.Security.Cryptography.Algorithms.dll
packages\System.Security.Cryptography.Encoding.4.3.0\lib\net46\System.Security.Cryptography.Encoding.dll
packages\System.Security.Cryptography.Primitives.4.3.0\lib\net46\System.Security.Cryptography.Primitives.dll
packages\System.Security.Cryptography.X509Certificates.4.3.0\lib\net461\System.Security.Cryptography.X509Certificates.dll
packages\System.Xml.ReaderWriter.4.3.0\lib\net46\System.Xml.ReaderWriter.dll

**Comment by EamonNerbonne** [comment]
I admit, it's really ugly.  But it's not entirely unexpected, either. This is a side effect of the migration to .net standard 1.6.1 (i.e. .net core support).

You can explore this via the nuget website even without an install: https://www.nuget.org/packages/AvsAn/3.0.0 now has a dependency on https://www.nuget.org/packages/NETStandard.Library/1.6.1 - and that in turn has lots of dependencies.  I don't quite understand why *only* 25 dlls actually get installed, to be quite honest. 

I'm hoping there is some way to avoid taking all those dependencies, whilst simultaneously supporting both .net core and .net framework, *and* avoiding cross-compiling, but I'm not sure it's possible.

Cross-compiling is a pain, because it means that I (in theory anyhow) would need to test at least two dlls, and that means I'd need multiple test harnesses, etc, etc etc...

Not to mention that until VS2017 RTM my cross-compiling experiments ran into alot of tooling corner cases; if it's better now, then at least it's still rather novel.

**Comment by jfcardinal** [comment]
Thanks for the update. I've downgraded back to 2.2.0 and I'll stay there for now. I don't need net core support, and I don't want to increase the size of the installer.

**Comment by EamonNerbonne** [comment]
So I un-dusted the cross-compiling patch and it looks like it's much more doable now.

Perhaps you could test it?  https://www.nuget.org/packages/AvsAn/3.0.1-beta shoud be less nasty for .net 4.5 targets

**Comment by jfcardinal** [comment]
Thanks. I will test 3.0.1-beta, but probably not until tomorrow.

**Comment by EamonNerbonne** [comment]
Looks like it works; so I'm releasing that as https://www.nuget.org/packages/AvsAn/3.0.1 .

Thanks for the report!
