### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by nadavb** [EamonNerbonne/a-vs-an#3]
Is there a python porting?

**Comment by EamonNerbonne** [comment]
Not yet!

If you want to port it, I'd suggest starting from https://github.com/EamonNerbonne/a-vs-an/blob/master/A-vs-An/AvsAn-JsDemo/AvsAn-simple.js (assuming you only care about whether a word should be preceded by a or an, and no further statistics).

The simplest possible solution probably avoid encoding the dictionary as a string (which is really just a minification trick in JS).  If you're going for that, then run the JS e.g. in your browser console on the demo page, and serialize the "raw" representation to JSON.  `JSON.stringify(AvsAnSimple.raw)` should do the trick.  That datastructure is fairly self-explanatory, I hope, and otherwise the js file [query function](https://github.com/EamonNerbonne/a-vs-an/blob/master/A-vs-An/AvsAn-JsDemo/AvsAn-simple.js#L21) is just a few lines and illustrates how to navigate it.

**Comment by EamonNerbonne** [comment]
To be clear: pull requests & forks welcome!  I'm always curious where this ends up, so I'd love to hear if you can get around to it, but if not: no problem.

**Comment by nadavb** [comment]
#4 Done. Pull request for python was created.

**Comment by EamonNerbonne** [comment]
Will continue in PR.
